name: Generate Pacman Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *" 
  
  # Allows to manually run the job at any time
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Generates the snake/pacman animation
      - uses: Platane/snk@v3
        with:
          github_user_name: asikrshoudo
          outputs: |
            assets/github-pacman.svg
            assets/github-pacman-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the generated files to the repository
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add assets/github-pacman.svg
          git commit -m "chore: update pacman animation [skip ci]" || exit 0
          git push

